version: "3"
services:
  postgres:
    image: "postgres:latest"
  redis:
    image: "redis:latest"
  nginx:
    restart: always
    build:
      dockerfile: Dockerfile.dev
      context: ./nginx
    ports:
      - "8080:80"
  api:
    build:
      dockerfile: Dockerfile.dev
      context: ./server
    volumes: #For development changes to hot reload and not keep building images
      - /app/node_modules #lock node_modules dir
      - ./server:/app #load changes from server to app in image
    environment:
      - REDIS_HOST=redis #Put name of service instead of actual host IP
      - REDIS_PORT=6379
      - PGUSER=postgres #Default Postgres variables from Docker hub
      - PGHOST=postgres
      - PGDATABASE=postgres
      - PGPASSWORD=postgres_password
      - PGPORT=5432
  client:
    build:
      dockerfile: Dockerfile.dev
      context: ./client
    volumes:
      - /app/node_modules
      - ./client:/app
  worker:
    environment:
      - REDIS_HOST=redis
      - REDIS_PORT=6379
    build:
      dockerfile: Dockerfile.dev
      context: ./worker
    volumes:
      - /app/node_modules
      - ./worker:/app
